"""initial schema

Revision ID: cb227b2a12fc
Revises:
Create Date: 2026-08-08 15:13:37.090415
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb227b2a12fc"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repositories",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("default_branch", sa.String(length=255), nullable=True),
        sa.Column("vcs", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("is_watched", sa.Boolean(), nullable=False),
        sa.Column("last_scanned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repositories")),
    )
    op.create_index(op.f("ix_repositories_name"), "repositories", ["name"], unique=True)
    op.create_index(op.f("ix_repositories_path"), "repositories", ["path"], unique=True)
    op.create_index(op.f("ix_repositories_status"), "repositories", ["status"], unique=False)
    op.create_table(
        "architectures",
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_architectures_repository_id_repositories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("repository_id", name=op.f("pk_architectures")),
    )
    op.create_table(
        "files",
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("language", sa.String(length=64), nullable=True),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("mtime", sa.Float(), nullable=False),
        sa.Column("is_generated", sa.Boolean(), nullable=False),
        sa.Column("is_binary", sa.Boolean(), nullable=False),
        sa.Column("encoding", sa.String(length=32), nullable=True),
        sa.Column("line_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("extra", sa.JSON(), nullable=False),
        sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_files_repository_id_repositories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_files")),
    )
    op.create_index(op.f("ix_files_language"), "files", ["language"], unique=False)
    op.create_index(op.f("ix_files_repository_id"), "files", ["repository_id"], unique=False)
    op.create_index(op.f("ix_files_sha256"), "files", ["sha256"], unique=False)
    op.create_index("uq_files_repo_path", "files", ["repository_id", "path"], unique=True)
    op.create_table(
        "modules",
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("path_prefix", sa.String(length=1024), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("extra", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_modules_repository_id_repositories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_modules")),
        sa.UniqueConstraint("repository_id", "name", name="uq_modules_repo_name"),
    )
    op.create_index(op.f("ix_modules_name"), "modules", ["name"], unique=False)
    op.create_index(op.f("ix_modules_repository_id"), "modules", ["repository_id"], unique=False)
    op.create_table(
        "repository_memory",
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("architecture_summary", sa.Text(), nullable=False),
        sa.Column("module_summaries", sa.JSON(), nullable=False),
        sa.Column("conventions", sa.JSON(), nullable=False),
        sa.Column("patterns", sa.JSON(), nullable=False),
        sa.Column("statistics", sa.JSON(), nullable=False),
        sa.Column("extra", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_repository_memory_repository_id_repositories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("repository_id", name=op.f("pk_repository_memory")),
    )
    op.create_table(
        "module_dependencies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("source_module_id", sa.Uuid(), nullable=False),
        sa.Column("target_module_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_module_dependencies_repository_id_repositories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_module_id"],
            ["modules.id"],
            name=op.f("fk_module_dependencies_source_module_id_modules"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_module_id"],
            ["modules.id"],
            name=op.f("fk_module_dependencies_target_module_id_modules"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_module_dependencies")),
        sa.UniqueConstraint(
            "source_module_id", "target_module_id", "kind", name="uq_moddep_pair_kind"
        ),
    )
    op.create_index("ix_moddep_source", "module_dependencies", ["source_module_id"], unique=False)
    op.create_index("ix_moddep_target", "module_dependencies", ["target_module_id"], unique=False)
    op.create_index(
        op.f("ix_module_dependencies_repository_id"),
        "module_dependencies",
        ["repository_id"],
        unique=False,
    )
    op.create_table(
        "module_files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("module_id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
            name=op.f("fk_module_files_file_id_files"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["modules.id"],
            name=op.f("fk_module_files_module_id_modules"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_module_files")),
        sa.UniqueConstraint("module_id", "file_id", name="uq_module_files_pair"),
    )
    op.create_index("ix_module_files_file", "module_files", ["file_id"], unique=False)
    op.create_index("ix_module_files_module", "module_files", ["module_id"], unique=False)
    op.create_table(
        "symbols",
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("qualified_name", sa.String(length=1024), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("language", sa.String(length=64), nullable=True),
        sa.Column("visibility", sa.String(length=16), nullable=True),
        sa.Column("is_exported", sa.Boolean(), nullable=False),
        sa.Column("is_async", sa.Boolean(), nullable=False),
        sa.Column("is_abstract", sa.Boolean(), nullable=False),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.Column("start_col", sa.Integer(), nullable=False),
        sa.Column("end_col", sa.Integer(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("docstring", sa.Text(), nullable=True),
        sa.Column("signature", sa.Text(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"], ["files.id"], name=op.f("fk_symbols_file_id_files"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["symbols.id"],
            name=op.f("fk_symbols_parent_id_symbols"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_symbols_repository_id_repositories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_symbols")),
    )
    op.create_index(op.f("ix_symbols_file_id"), "symbols", ["file_id"], unique=False)
    op.create_index(op.f("ix_symbols_kind"), "symbols", ["kind"], unique=False)
    op.create_index(op.f("ix_symbols_parent_id"), "symbols", ["parent_id"], unique=False)
    op.create_index(op.f("ix_symbols_qualified_name"), "symbols", ["qualified_name"], unique=False)
    op.create_index("ix_symbols_repo_kind", "symbols", ["repository_id", "kind"], unique=False)
    op.create_index("ix_symbols_repo_name", "symbols", ["repository_id", "name"], unique=False)
    op.create_index(op.f("ix_symbols_repository_id"), "symbols", ["repository_id"], unique=False)
    op.create_index(
        "uq_symbols_repo_file_name",
        "symbols",
        ["repository_id", "file_id", "qualified_name"],
        unique=True,
    )
    op.create_table(
        "dependencies",
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("source_file_id", sa.Uuid(), nullable=True),
        sa.Column("target_file_id", sa.Uuid(), nullable=True),
        sa.Column("source_symbol_id", sa.Uuid(), nullable=True),
        sa.Column("target_symbol_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=1024), nullable=False),
        sa.Column("target_name", sa.String(length=1024), nullable=True),
        sa.Column("is_resolved", sa.Boolean(), nullable=False),
        sa.Column("is_external", sa.Boolean(), nullable=False),
        sa.Column("line", sa.Integer(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_dependencies_repository_id_repositories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["files.id"],
            name=op.f("fk_dependencies_source_file_id_files"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_symbol_id"],
            ["symbols.id"],
            name=op.f("fk_dependencies_source_symbol_id_symbols"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_file_id"],
            ["files.id"],
            name=op.f("fk_dependencies_target_file_id_files"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_symbol_id"],
            ["symbols.id"],
            name=op.f("fk_dependencies_target_symbol_id_symbols"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dependencies")),
    )
    op.create_index(
        "ix_dependencies_repo_kind", "dependencies", ["repository_id", "kind"], unique=False
    )
    op.create_index(
        op.f("ix_dependencies_repository_id"), "dependencies", ["repository_id"], unique=False
    )
    op.create_index("ix_dependencies_target_file", "dependencies", ["target_file_id"], unique=False)
    op.create_index(
        "uq_dependencies_src_name",
        "dependencies",
        ["repository_id", "source_symbol_id", "name", "kind"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_dependencies_src_name", table_name="dependencies")
    op.drop_index("ix_dependencies_target_file", table_name="dependencies")
    op.drop_index(op.f("ix_dependencies_repository_id"), table_name="dependencies")
    op.drop_index("ix_dependencies_repo_kind", table_name="dependencies")
    op.drop_table("dependencies")
    op.drop_index("uq_symbols_repo_file_name", table_name="symbols")
    op.drop_index(op.f("ix_symbols_repository_id"), table_name="symbols")
    op.drop_index("ix_symbols_repo_name", table_name="symbols")
    op.drop_index("ix_symbols_repo_kind", table_name="symbols")
    op.drop_index(op.f("ix_symbols_qualified_name"), table_name="symbols")
    op.drop_index(op.f("ix_symbols_parent_id"), table_name="symbols")
    op.drop_index(op.f("ix_symbols_kind"), table_name="symbols")
    op.drop_index(op.f("ix_symbols_file_id"), table_name="symbols")
    op.drop_table("symbols")
    op.drop_index("ix_module_files_module", table_name="module_files")
    op.drop_index("ix_module_files_file", table_name="module_files")
    op.drop_table("module_files")
    op.drop_index(op.f("ix_module_dependencies_repository_id"), table_name="module_dependencies")
    op.drop_index("ix_moddep_target", table_name="module_dependencies")
    op.drop_index("ix_moddep_source", table_name="module_dependencies")
    op.drop_table("module_dependencies")
    op.drop_table("repository_memory")
    op.drop_index(op.f("ix_modules_repository_id"), table_name="modules")
    op.drop_index(op.f("ix_modules_name"), table_name="modules")
    op.drop_table("modules")
    op.drop_index("uq_files_repo_path", table_name="files")
    op.drop_index(op.f("ix_files_sha256"), table_name="files")
    op.drop_index(op.f("ix_files_repository_id"), table_name="files")
    op.drop_index(op.f("ix_files_language"), table_name="files")
    op.drop_table("files")
    op.drop_table("architectures")
    op.drop_index(op.f("ix_repositories_status"), table_name="repositories")
    op.drop_index(op.f("ix_repositories_path"), table_name="repositories")
    op.drop_index(op.f("ix_repositories_name"), table_name="repositories")
    op.drop_table("repositories")
    # ### end Alembic commands ###
