import { Identifiable } from '../shared';

// Tag types
export type TagType = 'shot' | 'delivery' | 'player' | 'event' | 'team' | 'venue';
export type TagStatus = 'pending' | 'approved' | 'rejected';

export interface VideoTag extends Identifiable {
  videoId: string;
  videoTitle?: string;
  type: TagType;
  label: string;
  
  // Timing
  startTime: number; // seconds
  endTime?: number; // seconds
  duration?: number; // seconds
  
  // Confidence
  confidence?: number; // 0-100
  isAutoGenerated: boolean;
  isVerified: boolean;
  
  // Metadata
  metadata?: TagMetadata;
  
  // Stats
  views?: number;
  clicks?: number;
  
  // Moderation
  status: TagStatus;
  verifiedBy?: string;
  verifiedAt?: string;
  rejectedReason?: string;
}

export interface TagMetadata {
  // For shot tags
  shotDirection?: 'straight' | 'cover' | 'square' | 'leg' | 'fine' | 'pull' | 'hook';
  shotType?: 'drive' | 'cut' | 'pull' | 'squarecut' | 'sweep' | 'reverse' | 'flick' | 'glance';
  
  // For delivery tags
  deliveryType?: 'fast' | 'short' | 'full' | 'yorker' | 'bouncer' | 'slower' | 'offspin' | 'legspin';
  deliveryLine?: 'good' | 'back_of_length' | 'short' | 'full_toss' | 'yorker';
  deliveryLength?: number; // meters from batter
  
  // For player tags
  playerId?: string;
  playerName?: string;
  teamId?: string;
  teamName?: string;
  role?: string;
  
  // For event tags
  ballNumber?: number;
  overNumber?: number;
  runsScored?: number;
  isWicket?: boolean;
  isBoundary?: boolean;
}

export interface TagCategory {
  id: string;
  name: string;
  type: TagType;
  subTags: string[];
  description?: string;
  imageUrl?: string;
}