// Shared exports for CricketIQ Microservices

export * from './types/index.js';
export { 
  generateId, 
  isValidId, 
  getCurrentTimestamp, 
  formatDate, 
  getDaysDifference, 
  addDays,
  isValidEmail,
  isValidPhone,
  isValidPassword,
  isValidName,
  capitalize,
  toSnakeCase,
  toCamelCase,
  truncate,
  chunkArray,
  uniqueBy,
  deepClone,
  mergeObjects,
  omit,
  pick,
  calculatePagination,
  getOffset,
  sortArray,
  AppError,
  handleError,
  generateFileName,
  getFileSize,
  formatNumber,
  formatCurrency,
  calculatePercentage,
  calculateBattingAverage,
  calculateStrikeRate,
  calculateEconomyRate,
  calculateBowlingAverage,
  getCricketFormatOvers,
  PaginationSchema,
  IdSchema,
  NameSchema,
  ContactSchema,
  AddressSchema,
  QueryParamsSchema,
  PaginationParams,
  QueryParams as UtilsQueryParams
} from './utils/index.js';
